### ISSUE TITLE
feat: support multiple methods per endpoint

### ISSUE THREAD

**Issue by tommytroen** [nais/krakend#34]
Today we only allow one path and one method in an ApiEndpoint endpoint, so if you have a endpoint which should allow multiple methods you cannot configure that as the webhook will deny the request. See slack thread for context:
https://nav-it.slack.com/archives/C5KUST8N6/p1705587556521019?thread_ts=1705584942.731189&cid=C5KUST8N6  

Krakend supports endpoints listening to multiple methods: https://www.krakend.io/docs/endpoints/#endpoints-listening-to-multiple-methods

The webhook should be fixed to allow an endpoint to have multiple methods or have multiple endpoints with the same path and different methods. Our spec should probably be changed to allow multiple methods in one endpoint for simplicity. Example:
```yaml
  endpoints:
    - path: /app1/somepath
      methods: 
        - GET
        - POST
      backendHost: http://app1
      backendPath: /api/somepath
```
